import { CodeCategory } from './types';

export const CODE_CATEGORIES: Record<string, CodeCategory> = {
  game: {
    id: 'game',
    title: 'Fun Games',
    description: 'Interactive games to play and learn from',
    icon: 'Gamepad2',
    usedIndices: [],
    recipes: [
      { id: 'g1', text: 'Create a whack-a-mole game with colorful moles' },
      { id: 'g2', text: 'Make a memory card matching game with animals' },
      { id: 'g3', text: 'Build a simple snake game with fruits to collect' },
      { id: 'g4', text: 'Design a balloon popping game with different colors' },
      { id: 'g5', text: 'Create a catch the falling stars game' },
      { id: 'g6', text: 'Make a simple ping pong game' },
      { id: 'g7', text: 'Build a color matching puzzle game' },
      { id: 'g8', text: 'Design a bubble shooter game' },
      { id: 'g9', text: 'Create a simple maze game with a timer' },
      { id: 'g10', text: 'Make a word guessing game with hints' },
      { id: 'g11', text: 'Build a tic-tac-toe game with emojis' },
      { id: 'g12', text: 'Design a simple racing game with obstacles' },
      { id: 'g13', text: 'Create a math quiz game with animations' },
      { id: 'g14', text: 'Make a fruit slice game like Fruit Ninja' },
      { id: 'g15', text: 'Build a space shooter with friendly aliens' },
      { id: 'g16', text: 'Design a pattern matching game' },
      { id: 'g17', text: 'Create a simple platformer game' },
      { id: 'g18', text: 'Make a candy crush style matching game' },
      { id: 'g19', text: 'Build a typing practice game with animals' },
      { id: 'g20', text: 'Design a simon says memory game' },
      { id: 'g21', text: 'Create a puzzle sliding game with numbers' },
      { id: 'g22', text: 'Make a basketball shooting game' },
      { id: 'g23', text: 'Build a rock, paper, scissors game' },
      { id: 'g24', text: 'Design a card flipping memory game' },
      { id: 'g25', text: 'Create a dodge the obstacles game' },
      { id: 'g26', text: 'Make a connect four game' },
      { id: 'g27', text: 'Build a breakout game' },
      { id: 'g28', text: 'Design a memory matching game with pictures' },
      { id: 'g29', text: 'Create a puzzle game with moving blocks' },
      { id: 'g30', text: 'Make a number guessing game' },
      { id: 'g31', text: 'Build a hangman game' },
      { id: 'g32', text: 'Design a crossword puzzle game' },
      { id: 'g33', text: 'Create a word search game' },
      { id: 'g34', text: 'Make a Sudoku game' },
      { id: 'g35', text: 'Build a jigsaw puzzle game' },
      { id: 'g36', text: 'Design a minesweeper game' },
      { id: 'g37', text: 'Create a solitaire card game' },
      { id: 'g38', text: 'Make a chess game' },
      { id: 'g39', text: 'Build a checkers game' },
      { id: 'g40', text: 'Design a backgammon game' },
      { id: 'g41', text: 'Create a poker game' },
      { id: 'g42', text: 'Make a blackjack game' },
      { id: 'g43', text: 'Build a roulette game' },
      { id: 'g44', text: 'Design a slot machine game' },
      { id: 'g45', text: 'Create a bingo game' },
      { id: 'g46', text: 'Make a lotto game' },
      { id: 'g47', text: 'Build a trivia game' },
      { id: 'g48', text: 'Design a quiz game' },
      { id: 'g49', text: 'Create a puzzle game' },
      { id: 'g50', text: 'Make a strategy game' }
    ]
  },
  animation: {
    id: 'animation',
    title: 'Cool Animations',
    description: 'Animated effects and transitions',
    icon: 'Sparkles',
    usedIndices: [],
    recipes: [
      { id: 'a1', text: 'Create a bouncing ball animation with color changes' },
      { id: 'a2', text: 'Make a growing flower animation' },
      { id: 'a3', text: 'Build a snow falling animation with wind effect' },
      { id: 'a4', text: 'Design a rocket launch animation with smoke' },
      { id: 'a5', text: 'Create a fireworks display animation' },
      { id: 'a6', text: 'Make an animation of fish swimming in an aquarium' },
      { id: 'a7', text: 'Build a spinning windmill with moving clouds' },
      { id: 'a8', text: 'Design a daylight to nighttime transition animation' },
      { id: 'a9', text: 'Create a loading animation with colorful shapes' },
      { id: 'a10', text: 'Make water ripple effects animation' },
      { id: 'a11', text: 'Build a flying bird animation with flapping wings' },
      { id: 'a12', text: 'Design a butterfly life cycle animation' },
      { id: 'a13', text: 'Create a balloon floating upwards animation' },
      { id: 'a14', text: 'Make a bouncing text animation' },
      { id: 'a15', text: 'Build a jumping character animation' },
      { id: 'a16', text: 'Design animated weather icons' },
      { id: 'a17', text: 'Create a rotating solar system animation' },
      { id: 'a18', text: 'Make a confetti explosion animation' },
      { id: 'a19', text: 'Design a falling leaves animation for autumn' },
      { id: 'a20', text: 'Create a train moving across a landscape animation' },
      { id: 'a21', text: 'Make a typing text effect animation' },
      { id: 'a22', text: 'Build a beach scene with animated waves' },
      { id: 'a23', text: 'Design an animated clock with moving hands' },
      { id: 'a24', text: 'Create a hot air balloon rising animation' },
      { id: 'a25', text: 'Make stars twinkling in the night sky animation' },
      { id: 'a26', text: 'Build a rainbow forming after rain animation' },
      { id: 'a27', text: 'Design animated traffic lights changing colors' },
      { id: 'a28', text: 'Create a book with page turning animation' },
      { id: 'a29', text: 'Make a carousel with rotating animals animation' },
      { id: 'a30', text: 'Build a walking robot animation' },
      { id: 'a31', text: 'Design a bubble blowing and popping animation' },
      { id: 'a32', text: 'Create a beating heart animation' },
      { id: 'a33', text: 'Make a campfire with flickering flames animation' },
      { id: 'a34', text: 'Build an animated progress bar with characters' },
      { id: 'a35', text: 'Design a volcano eruption animation' },
      { id: 'a36', text: 'Create a roller coaster ride animation' },
      { id: 'a37', text: 'Make a slide-in menu animation' },
      { id: 'a38', text: 'Build a popcorn popping animation' },
      { id: 'a39', text: 'Design a flip card animation with information' },
      { id: 'a40', text: 'Create a plant growing from seed animation' },
      { id: 'a41', text: 'Make animated emojis with changing expressions' },
      { id: 'a42', text: 'Build a raindrop falling animation with splashes' },
      { id: 'a43', text: 'Design an animated music visualizer' },
      { id: 'a44', text: 'Create a morphing shapes animation' },
      { id: 'a45', text: 'Make a fireflies animation' },
      { id: 'a46', text: 'Build a smoke animation' },
      { id: 'a47', text: 'Design a lightning animation' },
      { id: 'a48', text: 'Create a clouds animation' },
      { id: 'a49', text: 'Make a sun animation' },
      { id: 'a50', text: 'Build a moon animation' }
    ]
  },
  interactive: {
    id: 'interactive',
    title: 'Interactive Apps',
    description: 'Apps that respond to your input',
    icon: 'MousePointer2',
    usedIndices: [],
    recipes: [
      { id: 'i1', text: 'Create a color mixer with sliders' },
      { id: 'i2', text: 'Make a drawing canvas with brushes' },
      { id: 'i3', text: 'Build a music maker with buttons' },
      { id: 'i4', text: 'Design a pet customization tool' },
      { id: 'i5', text: 'Create a sticker maker app' },
      { id: 'i6', text: 'Make a simple paint program' },
      { id: 'i7', text: 'Build a character creator' },
      { id: 'i8', text: 'Design an emoji mood picker' },
      { id: 'i9', text: 'Create a virtual piano' },
      { id: 'i10', text: 'Make a weather dashboard' },
      { id: 'i11', text: 'Build a todo list with emojis' },
      { id: 'i12', text: 'Design a photo filter app' },
      { id: 'i13', text: 'Create a voice pitch changer' },
      { id: 'i14', text: 'Make a pattern generator' },
      { id: 'i15', text: 'Build a virtual pet simulator' },
      { id: 'i16', text: 'Design a story creator' },
      { id: 'i17', text: 'Create a simple calculator' },
      { id: 'i18', text: 'Make a digital clock designer' },
      { id: 'i19', text: 'Build an avatar creator' },
      { id: 'i20', text: 'Design a sound board' },
      { id: 'i21', text: 'Create a word cloud generator' },
      { id: 'i22', text: 'Make a comic strip creator' },
      { id: 'i23', text: 'Build a music visualizer' },
      { id: 'i24', text: 'Design a card maker' },
      { id: 'i25', text: 'Create a maze generator' },
      { id: 'i26', text: 'Make a simple notepad app' },
      { id: 'i27', text: 'Build a timer app' },
      { id: 'i28', text: 'Design a stop watch app' },
      { id: 'i29', text: 'Create a unit converter app' },
      { id: 'i30', text: 'Make a currency converter app' },
      { id: 'i31', text: 'Build a calculator with scientific functions' },
      { id: 'i32', text: 'Design a simple text editor' },
      { id: 'i33', text: 'Create a notepad app with saving features' },
      { id: 'i34', text: 'Make a simple to-do list manager' },
      { id: 'i35', text: 'Build a basic calendar app' },
      { id: 'i36', text: 'Design a simple contact list app' },
      { id: 'i37', text: 'Create a note-taking app with organization' },
      { id: 'i38', text: 'Make a simple task manager app' },
      { id: 'i39', text: 'Build a basic expense tracker app' },
      { id: 'i40', text: 'Design a simple fitness tracker app' },
      { id: 'i41', text: 'Create a basic meditation app' },
      { id: 'i42', text: 'Make a simple sleep tracker app' },
      { id: 'i43', text: 'Build a basic recipe app' },
      { id: 'i44', text: 'Design a simple book reader app' },
      { id: 'i45', text: 'Create a basic news reader app' },
      { id: 'i46', text: 'Make a simple weather app' },
      { id: 'i47', text: 'Build a basic map app' },
      { id: 'i48', text: 'Design a simple social media app' },
      { id: 'i49', text: 'Create a basic messaging app' },
      { id: 'i50', text: 'Make a simple email app' }
    ]
  },
  art: {
    id: 'art',
    title: 'Creative Art',
    description: 'Make beautiful digital art',
    icon: 'Palette',
    usedIndices: [],
    recipes: [
      { id: 'r1', text: 'Create a kaleidoscope maker' },
      { id: 'r2', text: 'Make a mandala designer' },
      { id: 'r3', text: 'Build a pixel art editor' },
      { id: 'r4', text: 'Design a fractal tree generator' },
      { id: 'r5', text: 'Create a symmetry painter' },
      { id: 'r6', text: 'Make a rainbow pattern maker' },
      { id: 'r7', text: 'Build a geometric art creator' },
      { id: 'r8', text: 'Design a spirograph tool' },
      { id: 'r9', text: 'Create an abstract art generator' },
      { id: 'r10', text: 'Make a constellation drawer' },
      { id: 'r11', text: 'Build a flower pattern maker' },
      { id: 'r12', text: 'Design a crystal generator' },
      { id: 'r13', text: 'Create a mosaic maker' },
      { id: 'r14', text: 'Make a bubble art creator' },
      { id: 'r15', text: 'Build a string art simulator' },
      { id: 'r16', text: 'Design a wave pattern generator' },
      { id: 'r17', text: 'Create a spray paint simulator' },
      { id: 'r18', text: 'Make a zentangle designer' },
      { id: 'r19', text: 'Build a sacred geometry creator' },
      { id: 'r20', text: 'Design a tie-dye simulator' },
      { id: 'r21', text: 'Create a crystal growth simulator' },
      { id: 'r22', text: 'Make a watercolor effect painter' },
      { id: 'r23', text: 'Build a neon light designer' },
      { id: 'r24', text: 'Design a rainbow spiral maker' },
      { id: 'r25', text: 'Create a stained glass designer' },
      { id: 'r26', text: 'Make a 3D model creator' },
      { id: 'r27', text: 'Build a virtual sculpting tool' },
      { id: 'r28', text: 'Design a digital painting app' },
      { id: 'r29', text: 'Create a custom brush maker' },
      { id: 'r30', text: 'Make a digital drawing pad' },
      { id: 'r31', text: 'Build a photo editor with filters and effects' },
      { id: 'r32', text: 'Design a graphic design tool with layers' },
      { id: 'r33', text: 'Create a vector graphics editor' },
      { id: 'r34', text: 'Make a 3D animation creator' },
      { id: 'r35', text: 'Build a virtual reality art studio' },
      { id: 'r36', text: 'Design a augmented reality art experience' },
      { id: 'r37', text: 'Create a custom font designer' },
      { id: 'r38', text: 'Make a digital calligraphy tool' },
      { id: 'r39', text: 'Build a logo maker with text and shapes' },
      { id: 'r40', text: 'Design a poster maker with templates' },
      { id: 'r41', text: 'Create a custom sticker maker' },
      { id: 'r42', text: 'Make a digital scrapbooking tool' },
      { id: 'r43', text: 'Build a custom card maker' },
      { id: 'r44', text: 'Design a custom invitation maker' },
      { id: 'r45', text: 'Create a custom banner maker' },
      { id: 'r46', text: 'Make a custom flyer maker' },
      { id: 'r47', text: 'Build a custom brochure maker' },
      { id: 'r48', text: 'Design a custom business card maker' },
      { id: 'r49', text: 'Create a custom letterhead maker' },
      { id: 'r50', text: 'Make a custom envelope maker' }
    ]
  }
};